/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiutscuaca.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author hahn
 */
public class FrmCuaca extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuaca
     */
    public FrmCuaca() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuaca = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSuhuMaks = new javax.swing.JLabel();
        lblSuhuMin = new javax.swing.JLabel();
        lblKecepatan = new javax.swing.JLabel();
        lblKelembapan = new javax.swing.JLabel();
        lblTekanan = new javax.swing.JLabel();
        cbWaktu = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuHelp = new javax.swing.JMenuItem();
        MenuAbout = new javax.swing.JMenuItem();
        MenuInput = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCuaca.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblCuaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuaca.setText("Monitor Cuaca");

        lblHari.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHari.setText("  ");

        lblSuhu.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        lblSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Suhu maksimum");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Suhu minimum");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Kecepatan angin");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Kelembapan");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Tekanan udara");

        lblSuhuMaks.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblSuhuMaks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSuhuMaks.setText("  ");

        lblSuhuMin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblSuhuMin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSuhuMin.setText("  ");

        lblKecepatan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblKecepatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKecepatan.setText("  ");

        lblKelembapan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblKelembapan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKelembapan.setText("  ");

        lblTekanan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTekanan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTekanan.setText("  ");

        cbWaktu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hari ini", "Besok" }));
        cbWaktu.setEnabled(false);
        cbWaktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbWaktuActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piiiutscuaca/res/04n.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        jLabel15.setText("broken clouds");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel15))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSuhuMaks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTekanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKelembapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKecepatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSuhuMin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lblHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                        .addComponent(cbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCuaca)
                    .addComponent(cbWaktu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHari)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblSuhuMaks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblSuhuMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblKecepatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblKelembapan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTekanan)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Kota");

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        jMenu5.setText("File");

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu5.add(MenuExit);

        jMenuBar4.add(jMenu5);

        jMenu6.setText("Help");

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });
        jMenu6.add(MenuHelp);

        MenuAbout.setText("About");
        MenuAbout.setBorderPainted(true);
        MenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAboutActionPerformed(evt);
            }
        });
        jMenu6.add(MenuAbout);

        MenuInput.setText("Input Data");
        MenuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuInputActionPerformed(evt);
            }
        });
        jMenu6.add(MenuInput);

        jMenuBar4.add(jMenu6);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:
        DlgHelp menuHelp = new DlgHelp();
        menuHelp.setLocationRelativeTo(null);
        menuHelp.setVisible(true);
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n" + "Regy Mahmud Azis" + "\n" + "NIM 1641805");
    }//GEN-LAST:event_MenuAboutActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
                
                try{
                Connection conn = (Connection)piiiutscuaca.koneksi.koneksi.configDB();
                String sql = "select * from t_cuaca where nama_kota='"+txtInput.getText()+"'";
                Statement sta = conn.createStatement();
                ResultSet rse = sta.executeQuery(sql);
                if(rse.next()){
                    lblCuaca.setText("Cuaca di " +rse.getString("nama_kota"));
                    lblSuhu.setText(rse.getString("suhu")+ (char)0x00B0 + "C");
                    lblSuhuMaks.setText(rse.getString("suhu_maks")+ (char)0x00B0 + " C");
                    lblSuhuMin.setText(rse.getString("suhu_min")+ (char)0x00B0 + " C");
                    lblKecepatan.setText(rse.getString("kecepatan_angin")+ " m/s");
                    lblKelembapan.setText(rse.getString("kelembapan")+ " %");
                    lblTekanan.setText(rse.getString("tekanan_udara")+ " hPa");
                    
                } else JOptionPane.showMessageDialog(null,"Punten data kota eta mah teu aya" + "\n" + 
                                                          "Mangga dicobian deui, Hatur Nuhun");

            }catch(Exception e) {
                e.printStackTrace();
            }         
          
    }//GEN-LAST:event_txtInputActionPerformed

    private void cbWaktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbWaktuActionPerformed
        // TODO add your handling code here:
        
        /*String hari = (String)cbWaktu.getSelectedItem();
        String kota = (String)txtInput.getText();
        
        if (txtInput.getText().equals("bandung") && cbWaktu.getSelectedItem().equals("Hari ini")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Hari ini");
            lblSuhu.setText("19.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("33.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("10.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("40.0 m/s");
            lblKelembapan.setText("200.2 %");
            lblTekanan.setText("300.2 hPa");
        }
        if (txtInput.getText().equals("bandung") && cbWaktu.getSelectedItem().equals("Besok")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Besok");
            lblSuhu.setText("29.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("43.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("20.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("50.0 m/s");
            lblKelembapan.setText("300.2 %");
            lblTekanan.setText("400.2 hPa");
        }
        if (txtInput.getText().equals("surabaya") && cbWaktu.getSelectedItem().equals("Hari ini")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Hari ini");
            lblSuhu.setText("27.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("40.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("20.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("10.0 m/s");
            lblKelembapan.setText("110.2 %");
            lblTekanan.setText("220.2 hPa");
        }
        if (txtInput.getText().equals("surabaya") && cbWaktu.getSelectedItem().equals("Besok")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Besok");
            lblSuhu.setText("37.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("50.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("30.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("20.0 m/s");
            lblKelembapan.setText("210.2 %");
            lblTekanan.setText("320.2 hPa");
        }
        if (txtInput.getText().equals("jakarta") && cbWaktu.getSelectedItem().equals("Hari ini")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Hari ini");
            lblSuhu.setText("40.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("50.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("30.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("30.0 m/s");
            lblKelembapan.setText("90.2 %");
            lblTekanan.setText("100.2 hPa");
        }
        if (txtInput.getText().equals("jakarta") && cbWaktu.getSelectedItem().equals("Besok")) {
            lblCuaca.setText("Cuaca di " +kota);
            lblHari.setText("Besok");
            lblSuhu.setText("50.0" + (char)0x00B0 + "C");
            lblSuhuMaks.setText("60.0" + (char)0x00B0 + "C");
            lblSuhuMin.setText("30.0" + (char)0x00B0 + "C");
            lblKecepatan.setText("40.0 m/s");
            lblKelembapan.setText("100.2 %");
            lblTekanan.setText("200.2 hPa");
        }*/
    }//GEN-LAST:event_cbWaktuActionPerformed

    private void MenuInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuInputActionPerformed
        // TODO add your handling code here:
        InputCuaca menuInput = new InputCuaca();
        menuInput.setLocationRelativeTo(null);
        menuInput.setVisible(true);
    }//GEN-LAST:event_MenuInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAbout;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuHelp;
    private javax.swing.JMenuItem MenuInput;
    private javax.swing.JComboBox cbWaktu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuaca;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblKecepatan;
    private javax.swing.JLabel lblKelembapan;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lblSuhuMaks;
    private javax.swing.JLabel lblSuhuMin;
    private javax.swing.JLabel lblTekanan;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
