/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piiiutscuaca.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hahn
 */
public class FrmCuaca extends javax.swing.JFrame {

    /**
     * Creates new form FrmCuaca
     */
    public FrmCuaca() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCuaca = new javax.swing.JLabel();
        lblHari = new javax.swing.JLabel();
        lblSuhu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblSuhuMaks = new javax.swing.JLabel();
        lblSuhuMin = new javax.swing.JLabel();
        lblKecepatan = new javax.swing.JLabel();
        lblKelembapan = new javax.swing.JLabel();
        lblTekanan = new javax.swing.JLabel();
        lblIcon = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        dcTanggal = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        txtInput = new javax.swing.JTextField();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        MenuExit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuHelp = new javax.swing.JMenuItem();
        MenuAbout = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        MenuLogin = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCuaca.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblCuaca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCuaca.setText("Monitor Cuaca");

        lblHari.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        lblHari.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHari.setText("  ");

        lblSuhu.setFont(new java.awt.Font("Roboto", 1, 50)); // NOI18N
        lblSuhu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setText("Suhu Maksimum");

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setText("Suhu Minimum");

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel7.setText("Kecepatan Angin");

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setText("Kelembapan");

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setText("Tekanan udara");

        lblSuhuMaks.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblSuhuMaks.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSuhuMaks.setText("  ");

        lblSuhuMin.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblSuhuMin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblSuhuMin.setText("  ");

        lblKecepatan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblKecepatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKecepatan.setText("  ");

        lblKelembapan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblKelembapan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblKelembapan.setText("  ");

        lblTekanan.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTekanan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTekanan.setText("  ");

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piiiutscuaca/res/04n.png"))); // NOI18N

        lblStatus.setFont(new java.awt.Font("Arial", 2, 14)); // NOI18N
        lblStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStatus.setText(" ");

        dcTanggal.setDateFormatString("yyyy-MM-dd");
        dcTanggal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dcTanggalPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblCuaca, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                            .addComponent(lblHari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblIcon))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblSuhu, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblSuhuMaks, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTekanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKelembapan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblKecepatan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSuhuMin, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCuaca)
                    .addComponent(dcTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblHari)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSuhu, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStatus))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblSuhuMaks))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblSuhuMin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblKecepatan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblKelembapan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblTekanan))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        dcTanggal.getAccessibleContext().setAccessibleDescription("");
        dcTanggal.getAccessibleContext().setAccessibleParent(this);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Kota");

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });

        jMenu5.setText("File");

        MenuExit.setText("Exit");
        MenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuExitActionPerformed(evt);
            }
        });
        jMenu5.add(MenuExit);

        jMenuBar4.add(jMenu5);

        jMenu6.setText("Help");

        MenuHelp.setText("Help");
        MenuHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpActionPerformed(evt);
            }
        });
        jMenu6.add(MenuHelp);

        MenuAbout.setText("About");
        MenuAbout.setBorderPainted(true);
        MenuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAboutActionPerformed(evt);
            }
        });
        jMenu6.add(MenuAbout);

        jMenuBar4.add(jMenu6);

        jMenu1.setText("Backend");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        MenuLogin.setText("Login");
        MenuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginActionPerformed(evt);
            }
        });
        jMenu1.add(MenuLogin);

        jMenuBar4.add(jMenu1);

        setJMenuBar(jMenuBar4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(151, 151, 151))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void MenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_MenuExitActionPerformed

    private void MenuHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpActionPerformed
        // TODO add your handling code here:
        DlgHelp menuHelp = new DlgHelp();
        menuHelp.setLocationRelativeTo(null);
        menuHelp.setVisible(true);
    }//GEN-LAST:event_MenuHelpActionPerformed

    private void MenuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Aplikasi Monitoring Cuaca" + "\n" + "Regy Mahmud Azis" + "\n" + "NIM 1641805");
    }//GEN-LAST:event_MenuAboutActionPerformed

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
                
                try{
                Connection conn = (Connection)piiiutscuaca.koneksi.koneksi.configDB();
                String sql = "select * from t_cuaca where nama_kota='"+txtInput.getText()+"'";
                Statement sta = conn.createStatement();
                ResultSet rse = sta.executeQuery(sql);
                if(rse.next()){
                    dcTanggal.setDate(rse.getDate("date"));
                    lblHari.setText("Tanggal " +(rse.getDate("date")));
                    lblCuaca.setText("Cuaca di " +rse.getString("nama_kota"));
                    lblSuhu.setText(rse.getString("suhu")+ (char)0x00B0 + "C");
                    lblSuhuMaks.setText(rse.getString("suhu_maks")+ (char)0x00B0 + " C");
                    lblSuhuMin.setText(rse.getString("suhu_min")+ (char)0x00B0 + " C");
                    lblKecepatan.setText(rse.getString("kecepatan_angin")+ " m/s");
                    lblKelembapan.setText(rse.getString("kelembapan")+ " %");
                    lblTekanan.setText(rse.getString("tekanan_udara")+ " hPa");
                    
                } else JOptionPane.showMessageDialog(null,"Punten data kota eta mah teu aya" + "\n" + 
                                                          "Mangga dicobian deui, Hatur Nuhun");

            }catch(Exception e) {
                e.printStackTrace();
            }         
          
    }//GEN-LAST:event_txtInputActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void MenuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginActionPerformed
        // TODO add your handling code here:
        login Login = new login();
        Login.setLocationRelativeTo(null);
        Login.setVisible(true);
    }//GEN-LAST:event_MenuLoginActionPerformed

    private void dcTanggalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dcTanggalPropertyChange
        // TODO add your handling code here:
        SimpleDateFormat fmt = new SimpleDateFormat("YYYY-MM-dd");
        if (evt.getNewValue() instanceof Date) {
            String tanggal = fmt.format((Date)evt.getNewValue());
            //System.out.println(tanggal);
            String nama_kota = txtInput.getText();
            
            try {
                Connection conn = (Connection)piiiutscuaca.koneksi.koneksi.configDB();
                String sql = "select * from t_cuaca where nama_kota='"+nama_kota+"' and date='"+tanggal+"' "+"LIMIT 1";
                //System.out.println(sql);
                Statement sta = conn.createStatement();
                ResultSet rse = sta.executeQuery(sql);
                
                if (!rse.next()) {
                    JOptionPane.showMessageDialog(null,"Punten data kota ieu di tanggal eta mah teu aya." + "\n" + 
                                                          "Mangga dicobian deui, Hatur Nuhun");
                } else {
                    
                    do {
                        ImageIcon icon = new ImageIcon(getClass().getResource("/piiiutscuaca/res/"+rse.getString("status")+".png"));
                        lblIcon.setIcon(icon);
                        lblStatus.setText(rse.getString("status"));
                        lblHari.setText("tanggal "+tanggal);
                        lblCuaca.setText("Cuaca di " +rse.getString("nama_kota"));
                        lblSuhu.setText(rse.getString("suhu")+ (char)0x00B0 + "C");
                        lblSuhuMaks.setText(rse.getString("suhu_maks")+ (char)0x00B0 + " C");
                        lblSuhuMin.setText(rse.getString("suhu_min")+ (char)0x00B0 + " C");
                        lblKecepatan.setText(rse.getString("kecepatan_angin")+ " m/s");
                        lblKelembapan.setText(rse.getString("kelembapan")+ " %");
                        lblTekanan.setText(rse.getString("tekanan_udara")+ " hPa");

                    } while(rse.next());
                }
            } catch(Exception e) {
                
            }
        }
        
                   
    }//GEN-LAST:event_dcTanggalPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCuaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCuaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAbout;
    private javax.swing.JMenuItem MenuExit;
    private javax.swing.JMenuItem MenuHelp;
    private javax.swing.JMenuItem MenuLogin;
    private com.toedter.calendar.JDateChooser dcTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCuaca;
    private javax.swing.JLabel lblHari;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblKecepatan;
    private javax.swing.JLabel lblKelembapan;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblSuhu;
    private javax.swing.JLabel lblSuhuMaks;
    private javax.swing.JLabel lblSuhuMin;
    private javax.swing.JLabel lblTekanan;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
